import Link from "next/link";
import { notFound } from "next/navigation";
import { ContentPage } from "@/components/marketing/ContentPage";
const data:Record<string,{title:string;body:string;sections:{title:string;body:string}[]}>= {
 billing:{title:'AI Billing',body:'A governed administrative layer for billing work, follow-up, and exceptions.',sections:[{title:'Workflow coordination',body:'Structure billing tasks so staff can see what is pending, blocked, or escalated.'},{title:'Traceable actions',body:'Keep operational actions connected to permissions, outcomes, and audit context.'},{title:'No invented outcomes',body:'Unverified payer or financial results are never represented as completed facts.'},{title:'Designed for measurable impact',body:'Future analytics can connect workflow completion to time, capacity, and financial outcomes.'}]},
 insurance:{title:'AI Insurance',body:'Support administrative insurance verification and payer follow-up through controlled workflows.',sections:[{title:'Verification support',body:'Organize verification requests and returned information without overstating coverage.'},{title:'Exception routing',body:'Move ambiguous or consequential cases to the appropriate human owner.'},{title:'Status visibility',body:'Give teams a consistent place to understand workflow state and next action.'},{title:'Audit context',body:'Keep operational activity observable for review and governance.'}]},
 'patient-engagement':{title:'AI Patient Engagement',body:'Coordinate administrative communication while keeping humans and policy in control.',sections:[{title:'Outreach coordination',body:'Support reminders, recall, responses, and follow-up workflows.'},{title:'Clear boundaries',body:'Administrative communication does not become autonomous clinical advice.'},{title:'Escalation',body:'Uncertain or consequential requests can be routed to staff.'},{title:'Operational visibility',body:'Teams can understand what communication work is pending and why.'}]},
 operations:{title:'AI Operations',body:'A command layer for the administrative work that moves through a healthcare organization.',sections:[{title:'Unified work',body:'Bring scheduling, intake, insurance, referrals, records, and communication into coherent operational patterns.'},{title:'Prioritized attention',body:'Surface work that needs people rather than filling the screen with vanity metrics.'},{title:'Agent accountability',body:'Represent agent involvement, confidence, escalation, and outcome explicitly.'},{title:'Expandable workforce',body:'Add specialized workers without redesigning the entire operating experience.'}]},
 compliance:{title:'AI Compliance',body:'Make the governance layer visible instead of treating it as a hidden backend concern.',sections:[{title:'Audit explorer',body:'Provide a structured experience for actor, action, resource, timestamp, request, and outcome.'},{title:'Access awareness',body:'Keep organization and permission context visible to authorized users.'},{title:'Human oversight',body:'Show when automation is escalated or requires human approval.'},{title:'Data minimization',body:'Avoid unnecessary exposure of sensitive information in operational views.'}]}
};
export function generateStaticParams(){return Object.keys(data).map(solution=>({solution}));}
export default async function SolutionPage({params}:{params:Promise<{solution:string}>}){const {solution}=await params;const item=data[solution];if(!item)notFound();return <ContentPage eyebrow="Healthcare solution" title={item.title} body={item.body} sections={item.sections}/>}
