import Link from "next/link";
import { FeatureCard, MarketingShell, TrustBand } from "@/components/marketing/MarketingShell";

const agents = ["Reception", "Scheduling", "Intake", "Insurance", "Prior Authorization", "Refills", "Records", "Referrals", "Recall", "Email"];
const outcomes = [
  ["Reduce administrative load", "Automate eligible repetitive work so staff can focus on exceptions, patients, and higher-value operations."],
  ["Keep humans in control", "Use explicit permissions, policy boundaries, confidence, and escalation rather than pretending AI is infallible."],
  ["Make work accountable", "Give every consequential workflow a clear operational trail so teams can understand what happened and why."]
] as const;

export default function HomePage() {
  return <MarketingShell>
    <main>
      <section className="overflow-hidden bg-slate-950 text-white">
        <div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28">
          <div><div className="inline-flex rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs font-semibold text-slate-300">AI workforce infrastructure for healthcare</div><h1 className="mt-7 max-w-3xl text-5xl font-black tracking-[-0.04em] sm:text-6xl lg:text-7xl">Your clinic’s AI workforce. <span className="text-slate-400">One intelligent operating system.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">HEZQARA coordinates specialized AI workers for healthcare administration — from scheduling and intake to insurance, referrals, records, and patient engagement.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/sign-up" className="inline-flex justify-center rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-slate-950">See HEZQARA in action</Link><Link href="/workforce" className="inline-flex justify-center rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-white hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white">Explore the AI workforce</Link></div><p className="mt-5 text-xs text-slate-500">Administrative automation only. Clinical decisions remain with qualified professionals.</p></div>
          <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-sm font-semibold">AI workforce</p><p className="mt-1 text-xs text-slate-500">Organization-scoped readiness</p></div><span className="rounded-full bg-white/10 px-2.5 py-1 text-xs text-slate-300">Governed</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{agents.map((agent, i) => <div key={agent} className="rounded-2xl border border-white/10 bg-slate-900/80 p-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-slate-400" aria-hidden="true"/><span className="text-xs font-semibold text-slate-200">{agent}</span></div><p className="mt-2 text-[11px] text-slate-500">Ready for governed workflows</p></div>)}</div><div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs font-semibold text-slate-400">Execution principle</p><p className="mt-2 text-sm leading-6 text-slate-300">The interface shows what the system can prove — not synthetic activity designed to look busy.</p></div></div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">One workforce, many workflows</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Move administrative work from queues to governed automation.</h2><p className="mt-4 text-base leading-7 text-slate-600">HEZQARA is designed around the work healthcare teams actually need to move: requests, follow-ups, coordination, verification, communication, and exceptions.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{outcomes.map(([title, body]) => <FeatureCard key={title} title={title} body={body}/>)}</div></section>
      <TrustBand />
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Built for the operating layer</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">From the first request to the final audit trail.</h2></div><div className="text-sm leading-7 text-slate-600">A patient-facing request can become a structured task, move through an authorized AI worker, escalate when required, and leave a traceable result. The system is designed to make automation observable instead of opaque.</div></div><div className="mt-10 grid gap-3 md:grid-cols-4">{[["01","Capture","Turn inbound work into structured operational context."],["02","Decide","Apply permissions, policy and confidence boundaries."],["03","Execute","Use approved tools and domain workflows."],["04","Account","Record outcome, escalation and audit context."]].map(([n,t,b])=><div key={n} className="rounded-2xl border border-slate-200 p-5"><span className="text-xs font-bold text-slate-400">{n}</span><h3 className="mt-8 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{b}</p></div>)}</div></section>
      <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-16 text-center sm:px-8"><h2 className="text-3xl font-black tracking-tight">See where your administrative workload can go next.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-slate-400">Start with a workflow. Expand into a workforce as the value becomes measurable.</p><Link href="/sign-up" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-slate-100">Start with HEZQARA</Link></div></section>
    </main>
  </MarketingShell>;
}
