"use client";
import {useEffect,useState} from "react";
import api from "@/lib/api";

type Summary={active:number;degraded:number;disabled:number;executions:number;failures:number;pending_approvals:number;policy_blocks:number};
type Capability={id:string;name:string;description:string;domain:string;owner:string;status:string;risk_tier:number;phi_classification:string;approval_required:boolean;escalation_required:boolean;updated_at:string};
export default function AIGovernancePage(){
 const [summary,setSummary]=useState<Summary|null>(null);const [caps,setCaps]=useState<Capability[]>([]);const [failures,setFailures]=useState<any[]>([]);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;Promise.all([api.get<Summary>("/api/v1/ai-governance/summary"),api.get<Capability[]>("/api/v1/ai-governance/capabilities?limit=50"),api.get<any[]>("/api/v1/ai-governance/failures?limit=10")]).then(([s,c,f])=>{if(live){setSummary(s);setCaps(c);setFailures(f)}}).catch(e=>live&&setError(e instanceof Error?e.message:"Unable to load AI governance")).finally(()=>live&&setLoading(false));return()=>{live=false}},[]);
 if(loading)return <div className="p-6 lg:p-10"><p className="text-sm text-slate-500">Loading AI governance…</p></div>;
 if(error)return <div className="p-6 lg:p-10"><div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}</div></div>;
 return <div className="p-6 lg:p-10"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Governance</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">AI Governance</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Evidence-backed health, capability controls, evaluation readiness and safety events. No production metric is fabricated.</p></header>
 <section aria-label="AI health" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Active",summary?.active??0],["Degraded",summary?.degraded??0],["Disabled",summary?.disabled??0],["Executions · 24h",summary?.executions??0]].map(([l,v])=><article key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-500">{l}</p><p className="mt-2 text-3xl font-black text-slate-950">{v}</p></article>)}</section>
 <section className="mt-6 grid gap-4 md:grid-cols-3">{[["Failures · 24h",summary?.failures??0],["Policy blocks · 24h",summary?.policy_blocks??0],["Pending approvals",summary?.pending_approvals??0]].map(([l,v])=><article key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-500">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></article>)}</section>
 <section className="mt-8"><div className="flex items-end justify-between"><div><h2 className="text-xl font-black">Capability registry</h2><p className="mt-1 text-sm text-slate-500">Tenant-scoped, versioned AI inventory.</p></div></div><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50"><tr>{["Capability","Domain","Risk","Status","Approval"].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{caps.length?caps.map(c=><tr key={c.id} className="border-b border-slate-100"><td className="px-4 py-4"><div className="font-semibold">{c.name}</div><div className="text-xs text-slate-500">{c.id}</div></td><td className="px-4 py-4">{c.domain}</td><td className="px-4 py-4">Tier {c.risk_tier}</td><td className="px-4 py-4">{c.status}</td><td className="px-4 py-4">{c.approval_required?"Required":"Policy governed"}</td></tr>):<tr><td colSpan={5} className="px-4 py-12 text-center text-slate-500">No AI capabilities are registered for this tenant.</td></tr>}</tbody></table></div></section>
 <section className="mt-8"><h2 className="text-xl font-black">Recent failures</h2><div className="mt-4 space-y-3">{failures.length?failures.map(f=><article key={f.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-4"><span className="font-semibold">{f.category}</span><span className="text-xs text-slate-500">{f.severity}</span></div><p className="mt-1 text-sm text-slate-600">{f.detail}</p></article>):<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No AI failures recorded in the current tenant.</div>}</div></section></div>;
}
