from typing import Any, Protocol
class AIProvider(Protocol):
    async def generate(self, *, system_prompt:str, user_input:str, model:str, temperature:float=0.0, max_tokens:int=1000)->str: ...
    async def structured_output(self, *, system_prompt:str, user_input:str, model:str, schema:dict[str,Any])->dict[str,Any]: ...
