"use client";

import {useMemo,useState} from "react";
import type {ReactNode} from "react";
import {api,type MetricTrace} from "@/lib/api";
import {useAnalytics} from "@/hooks/useAgents";
const money=(value:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const pct=(value:number|null)=>value==null?"—":`${(value*100).toFixed(1)}%`;
function Card({label,value,detail,onClick}:{label:string;value:string|number;detail:string;onClick?:()=>void}){return <button type="button" onClick={onClick} className="w-full rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-slate-300 hover:shadow-md disabled:cursor-default"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-3 text-3xl font-black tabular-nums text-slate-950">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></button>}
function Section({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{eyebrow}</p><h2 className="mt-1 text-xl font-black tracking-tight">{title}</h2></div>{children}</section>}
export default function AnalyticsPage(){
  const {summary,daily,financial,insurance,compliance,executive,catalog,loading,error,reload}=useAnalytics();
  const [trace,setTrace]=useState<MetricTrace|null>(null);const [traceLoading,setTraceLoading]=useState(false);const [traceError,setTraceError]=useState<string|null>(null);const [evidence,setEvidence]=useState(false);const [evidenceRows,setEvidenceRows]=useState<{id:string;created_at:string;action:string;resource_type:string;outcome:string}[]>([]);const [exporting,setExporting]=useState(false);
  const maxTrend=useMemo(()=>Math.max(1,...daily.map(d=>d.appointments_booked+d.calls+d.tasks_completed)),[daily]);
  const openTrace=async(key:string)=>{setTraceLoading(true);setTraceError(null);try{setTrace(await api.analytics.trace(key))}catch(e){setTraceError(e instanceof Error?e.message:"Unable to load source trace")}finally{setTraceLoading(false)}};
  const loadEvidence=async()=>{try{const r=await api.analytics.evidence();setEvidenceRows(r.events)}catch(e){setTraceError(e instanceof Error?e.message:"Unable to load compliance evidence")}};
  const download=async()=>{setExporting(true);try{const payload=await api.get<{format:string;window:{start:string;end:string};fields:string[];rows:Record<string,string|number|null>[]}>("/api/v1/analytics/export-data");const csv=[payload.fields.join(","),...payload.rows.map(row=>payload.fields.map(field=>{const value=row[field];const text=value==null?"":String(value);return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`hezqara-analytics-${payload.window.start.slice(0,10)}-${payload.window.end.slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}catch(e){setTraceError(e instanceof Error?e.message:"Unable to export analytics")}finally{setExporting(false)}};
  return <section className="space-y-10 p-5 sm:p-8">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Intelligence command center</p><h1 className="mt-2 text-3xl font-black tracking-tight">Measured performance</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Tenant-scoped operational, revenue-cycle, insurance and compliance intelligence. Every value is derived from persisted source data; no synthetic or estimated metrics are shown.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void reload()} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Refresh</button><button type="button" disabled={exporting} onClick={()=>void download()} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{exporting?"Preparing…":"Export CSV"}</button></div></header>
    {error&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-white" />)}</div>:!summary||!financial||!insurance||!compliance||!executive?<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No analytics data available</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">The workspace will populate when organization-scoped source events are available.</p></div>:<>
      <div className="rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-500">Reporting window: <span className="font-semibold text-slate-700">{new Date(summary.window.start).toLocaleDateString()}</span> — <span className="font-semibold text-slate-700">{new Date(summary.window.end).toLocaleDateString()}</span>. Fresh through {new Date(summary.freshness).toLocaleTimeString()}.</div>
      <Section eyebrow="Executive view" title="What needs attention"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-slate-800">{executive.headline}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{executive.risks.length?executive.risks.map(r=><div key={r.key} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><span className="font-bold text-slate-900">{r.title}</span><span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">{r.severity}</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{r.explanation}</p><p className="mt-2 text-[11px] text-slate-400">Sources: {r.source_metrics.join(", ")}</p></div>):<p className="text-sm text-slate-500">No governed risk signals crossed the configured thresholds.</p>}</div></div></Section>
      <Section eyebrow="Operations" title="Operational trends"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{summary.metrics.filter(m=>m.category==="operations"||m.category==="AI workforce"||m.category==="workflow"||m.category==="communications").slice(0,8).map(m=><Card key={m.key} label={m.label} value={m.value??"—"} detail={`${m.definition} Source: ${m.source_tables.join(", ")}`} onClick={()=>m.drilldown&&void openTrace(m.key)}/>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Daily activity</h3><span className="text-xs text-slate-400">Calls + bookings + completed tasks</span></div><div className="mt-5 space-y-3">{daily.slice(-14).map(d=><div key={d.day} className="grid grid-cols-[5rem_1fr_4rem] items-center gap-3 text-xs"><span className="text-slate-500">{d.day}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{width:`${Math.min(100,((d.calls+d.appointments_booked+d.tasks_completed)/maxTrend)*100)}%`}} /></div><span className="text-right font-semibold tabular-nums">{d.calls+d.appointments_booked+d.tasks_completed}</span></div>)}</div></div></Section>
      <Section eyebrow="Revenue cycle" title="Financial intelligence"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Charges" value={money(financial.charges_amount)} detail="Non-voided charges created in window." onClick={()=>void openTrace("charges_amount")}/><Card label="Payments" value={money(financial.payments_amount)} detail="Paid billing payments created in window." onClick={()=>void openTrace("payments_amount")}/><Card label="Open A/R" value={money(financial.open_ar_amount)} detail="Currently open A/R work-item amount."/><Card label="Denials" value={money(financial.denial_amount)} detail={`Denied claim count: ${financial.denied_claim_count}.`} onClick={()=>void openTrace("denial_amount")}/></div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Collection rate</p><p className="mt-2 text-3xl font-black">{pct(financial.collection_rate)}</p><p className="mt-2 text-sm text-slate-500">Payments collected divided by claims billed.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Claim denial rate</p><p className="mt-2 text-3xl font-black">{pct(financial.denial_rate)}</p><p className="mt-2 text-sm text-slate-500">Null when the denominator is not meaningful.</p></div></div></Section>
      <Section eyebrow="Insurance" title="Coverage and authorization intelligence"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Eligibility success" value={pct(insurance.eligibility_success_rate)} detail={`${insurance.eligibility_verified} verified of ${insurance.eligibility_requests} requests.`} onClick={()=>void openTrace("eligibility_requests")}/><Card label="Eligibility failures" value={insurance.eligibility_failed} detail="Failure-class responses in the selected window."/><Card label="Authorization approval" value={pct(insurance.authorization_approval_rate)} detail={`${insurance.authorizations_approved} approved of ${insurance.authorizations_submitted} submitted.`} onClick={()=>void openTrace("authorizations_submitted")}/><Card label="Referrals completed" value={insurance.referrals_completed} detail={`${insurance.referrals_sent} referral records entered tracked states.`} onClick={()=>void openTrace("referrals_completed")}/></div></Section>
      <Section eyebrow="Compliance evidence" title="Auditable activity"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Audit events" value={compliance.audit_events} detail="Tenant-scoped immutable audit records." onClick={()=>void openTrace("audit_events")}/><Card label="Privileged" value={compliance.privileged_events} detail="Classified privileged actions."/><Card label="AI events" value={compliance.ai_events} detail="Events carrying AI/agent attribution."/><Card label="Failures" value={`${compliance.failed_events} (${pct(compliance.failure_rate)})`} detail="Explicitly failed, denied, rejected or error outcomes."/></div><button type="button" onClick={()=>{setEvidence(true);void loadEvidence()}} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Explore evidence</button>{evidence&&<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Time</th><th className="p-4">Action</th><th className="p-4">Resource</th><th className="p-4">Outcome</th></tr></thead><tbody>{evidenceRows.map(row=><tr key={row.id} className="border-b border-slate-100"><td className="p-4 text-slate-500">{new Date(row.created_at).toLocaleString()}</td><td className="p-4 font-semibold">{row.action}</td><td className="p-4">{row.resource_type}</td><td className="p-4">{row.outcome}</td></tr>)}</tbody></table>{!evidenceRows.length&&<p className="p-6 text-sm text-slate-500">No evidence records match the current window.</p>}</div>}</Section>
      <Section eyebrow="Governance" title="Metric catalog"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Metric</th><th className="p-4">Definition</th><th className="p-4">Formula</th><th className="p-4">Source</th><th className="p-4">Time</th></tr></thead><tbody>{catalog?.metrics.map(m=><tr key={m.key} className="border-b border-slate-100 align-top"><td className="p-4 font-bold">{m.label}</td><td className="p-4 text-slate-500">{m.definition}</td><td className="p-4 font-mono text-xs text-slate-500">{m.formula}</td><td className="p-4 text-slate-500">{m.source_tables.join(", ")}</td><td className="p-4 text-slate-500">{m.time_field}</td></tr>)}</tbody></table></div></Section>
    </>}
    {(traceLoading||trace||traceError)&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-4 sm:items-center"><div className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Source trace</p><h2 className="mt-1 text-xl font-black">{trace?.metric.label??"Loading trace"}</h2></div><button type="button" onClick={()=>{setTrace(null);setTraceError(null)}} className="rounded-lg border border-slate-200 px-3 py-1 text-sm">Close</button></div>{traceLoading&&<p className="mt-6 text-sm text-slate-500">Loading source contributions…</p>}{traceError&&<p className="mt-6 text-sm text-red-600">{traceError}</p>}{trace&&!traceLoading&&<><p className="mt-3 text-sm text-slate-500">{trace.metric.definition} Time field: <span className="font-mono text-xs">{trace.metric.time_field}</span>.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wider text-slate-400"><tr><th className="py-3">Day</th><th className="py-3">Status</th><th className="py-3">Count</th><th className="py-3">Amount</th></tr></thead><tbody>{trace.rows.map((row,i)=><tr key={`${row.day}-${row.status}-${i}`} className="border-b border-slate-100"><td className="py-3">{row.day}</td><td className="py-3">{row.status??"—"}</td><td className="py-3 tabular-nums">{row.count}</td><td className="py-3 tabular-nums">{row.amount==null?"—":money(row.amount)}</td></tr>)}</tbody></table></div></>}</div></div>}
  </section>;
}
