"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { cn } from "@/lib/cn";
import { Badge, Button, Card, StatusBadge } from "@/components/ui/primitives";
import { EXECUTION_LABELS, READINESS_LABELS, executionTone, readinessTone, type ExecutionState, type ReadinessState } from "@/types/ui";

export function AgentBadge({ label }: { label: string }) { return <Badge tone="neutral">AI · {label}</Badge>; }
export function AgentIdentity({ name, purpose }: { name: string; purpose?: string }) { return <div><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-semibold text-slate-950">{name}</h2><AgentBadge label="workforce" /></div>{purpose ? <p className="mt-1 text-sm text-slate-600">{purpose}</p> : null}</div>; }
export function AgentStatus({ state, kind = "readiness" }: { state: ReadinessState | ExecutionState; kind?: "readiness" | "execution" }) { const tone = kind === "readiness" ? readinessTone(state as ReadinessState) : executionTone(state as ExecutionState); const label = kind === "readiness" ? READINESS_LABELS[state as ReadinessState] : EXECUTION_LABELS[state as ExecutionState]; return <StatusBadge tone={tone} label={label} icon={kind === "execution" && state === "running" ? "↻" : "•"} />; }
export function ConfidenceIndicator({ value }: { value: number }) { const clamped = Math.max(0, Math.min(1, value)); return <div aria-label={`Confidence ${Math.round(clamped * 100)} percent`} className="space-y-1.5"><div className="flex justify-between text-xs font-medium text-slate-600"><span>Confidence</span><span>{Math.round(clamped * 100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-700" style={{ width: `${clamped * 100}%` }} /></div></div>; }
export function EscalationBanner({ children }: { children: ReactNode }) { return <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong className="font-semibold">Human attention required.</strong> <span>{children}</span></div>; }
export function ApprovalPanel({ title = "Approval required", children, onApprove, onReject }: { title?: string; children: ReactNode; onApprove?: () => void; onReject?: () => void }) { return <Card className="border-amber-200 p-5"><h3 className="font-semibold text-slate-950">{title}</h3><div className="mt-2 text-sm leading-6 text-slate-600">{children}</div>{onApprove || onReject ? <div className="mt-4 flex flex-wrap gap-2">{onApprove ? <Button onClick={onApprove}>Approve</Button> : null}{onReject ? <Button variant="secondary" onClick={onReject}>Reject</Button> : null}</div> : null}</Card>; }
export function ExecutionSummary({ agent, executionId, state }: { agent: string; executionId: string; state: ExecutionState }) { return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><AgentIdentity name={agent} /><AgentStatus state={state} kind="execution" /></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Execution ID</dt><dd className="mt-1 break-all font-mono text-xs text-slate-800">{executionId}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Runtime state</dt><dd className="mt-1 text-sm text-slate-800">{EXECUTION_LABELS[state]}</dd></div></dl></Card>; }
export function ExecutionTimeline({ items }: { items: Array<{ id: string; label: string; detail?: string; state?: ExecutionState }> }) { return <ol className="space-y-4">{items.map(item=><li key={item.id} className="flex gap-3"><span aria-hidden="true" className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-slate-400"/><div><p className="text-sm font-semibold text-slate-900">{item.label}{item.state ? <span className="ml-2"><AgentStatus state={item.state} kind="execution" /></span> : null}</p>{item.detail ? <p className="mt-1 text-sm leading-6 text-slate-600">{item.detail}</p> : null}</div></li>)}</ol>; }
export function ToolInvocationRow({ tool, outcome }: { tool: string; outcome?: string }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-3"><span className="font-mono text-xs text-slate-700">{tool}</span><span className="text-xs text-slate-500">{outcome ?? "Outcome not available"}</span></div>; }
export function HumanApprovalControl({ children, onConfirm }: { children: ReactNode; onConfirm?: () => void }) { return <div className="rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="text-sm leading-6 text-slate-700">{children}</p>{onConfirm ? <Button className="mt-3" onClick={onConfirm}>Confirm human approval</Button> : null}</div>; }
export function AIActivityIndicator({ label = "AI activity" }: { label?: string }) { return <span role="status" className="inline-flex items-center gap-2 text-xs font-medium text-slate-600"><span aria-hidden="true" className="h-2 w-2 animate-pulse rounded-full bg-sky-500" />{label}</span>; }

export function ConfirmationDialog({ open, title, description, confirmLabel = "Confirm", destructive = false, onConfirm, onClose, children }: { open: boolean; title: string; description?: string; confirmLabel?: string; destructive?: boolean; onConfirm: () => void; onClose: () => void; children?: ReactNode }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; const root = ref.current; const focusables = root?.querySelectorAll<HTMLElement>("button,[href],input,select,textarea,[tabindex]:not([tabindex='-1'])"); focusables?.[0]?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "Tab" && focusables?.length) { const first = focusables[0], last = focusables[focusables.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous?.focus(); }; }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="dialog-title" aria-describedby={description ? "dialog-description" : undefined} className="w-full max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-xl"><h2 id="dialog-title" className="text-lg font-semibold text-slate-950">{title}</h2>{description ? <p id="dialog-description" className="mt-2 text-sm leading-6 text-slate-600">{description}</p> : null}{children ? <div className="mt-4">{children}</div> : null}<div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={destructive ? "danger" : "primary"} onClick={onConfirm}>{confirmLabel}</Button></div></div></div>;
}
