import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/cn";

export function ContentContainer({ className, children }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("mx-auto w-full max-w-[1440px] px-4 sm:px-6 lg:px-8", className)}>{children}</div>; }
export function PageSection({ className, children }: HTMLAttributes<HTMLElement>) { return <section className={cn("py-6 sm:py-8", className)}>{children}</section>; }
export function Stack({ gap = "gap-4", className, children }: { gap?: string; className?: string; children: ReactNode }) { return <div className={cn("flex flex-col", gap, className)}>{children}</div>; }
export function Grid({ className, children }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("grid gap-4", className)}>{children}</div>; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2">{eyebrow ? <p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{eyebrow}</p> : null}</div><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h1>{description ? <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{description}</p> : null}</div>{actions ? <div className="flex shrink-0 flex-wrap gap-2">{actions}</div> : null}</header>; }
export function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) { return <nav aria-label="Breadcrumb" className="mb-4"><ol className="flex flex-wrap items-center gap-2 text-xs text-slate-500">{items.map((item,index)=><li key={`${item.label}-${index}`} className="flex items-center gap-2"><span aria-hidden="true">{index ? "/" : ""}</span>{item.href ? <a className="hover:text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-500" href={item.href}>{item.label}</a> : <span aria-current="page" className="font-medium text-slate-700">{item.label}</span>}</li>)}</ol></nav>; }
