import type { ReactNode } from "react";
import { cn } from "@/lib/cn";
import { Button, StatusBadge } from "@/components/ui/primitives";
import type { StatusTone } from "@/types/ui";

export function Alert({ title, children, tone = "info" }: { title?: string; children: ReactNode; tone?: StatusTone }) { return <div role="status" className="rounded-xl border border-slate-200 bg-white p-4"><StatusBadge tone={tone} label={title ?? "Notice"} />{children ? <p className="mt-2 text-sm leading-6 text-slate-700">{children}</p> : null}</div>; }
export function InlineNotice({ children, tone = "neutral" }: { children: ReactNode; tone?: StatusTone }) { return <div className={cn("rounded-lg border p-3 text-sm leading-6", tone === "danger" ? "border-rose-200 bg-rose-50 text-rose-900" : tone === "warning" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-slate-200 bg-slate-50 text-slate-700")} role="status">{children}</div>; }
export function Progress({ value, label }: { value: number; label?: string }) { const safe = Math.max(0, Math.min(100, value)); return <div className="space-y-2"><div className="flex justify-between text-xs font-medium text-slate-600"><span>{label ?? "Progress"}</span><span>{safe}%</span></div><div role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe} className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-700" style={{ width: `${safe}%` }} /></div></div>; }
export function Tabs({ items, value, onChange }: { items: Array<{ value: string; label: string }>; value: string; onChange: (value: string) => void }) { return <div role="tablist" aria-label="Section tabs" className="flex gap-1 overflow-x-auto border-b border-slate-200">{items.map(item=><button key={item.value} type="button" role="tab" aria-selected={value === item.value} onClick={()=>onChange(item.value)} className={cn("min-h-11 whitespace-nowrap border-b-2 px-3 text-sm font-semibold", value === item.value ? "border-slate-900 text-slate-950" : "border-transparent text-slate-500 hover:text-slate-800")}>{item.label}</button>)}</div>; }
export function Pagination({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) { return <nav aria-label="Pagination" className="flex items-center justify-between gap-3"><Button variant="secondary" disabled={page <= 1} onClick={()=>onChange(page - 1)}>Previous</Button><span className="text-xs text-slate-500">Page {page} of {totalPages}</span><Button variant="secondary" disabled={page >= totalPages} onClick={()=>onChange(page + 1)}>Next</Button></nav>; }
export function Stepper({ steps, current }: { steps: string[]; current: number }) { return <ol className="flex flex-col gap-3 sm:flex-row">{steps.map((step,index)=><li key={step} className={cn("flex items-center gap-2 text-sm", index <= current ? "font-semibold text-slate-900" : "text-slate-400")}><span className="grid h-7 w-7 place-items-center rounded-full border border-current text-xs">{index + 1}</span><span>{step}</span></li>)}</ol>; }
