-- Phase 7: governed interoperability and external integration state.
-- Historical migrations are immutable. All rows are tenant-owned through clinic_id.

CREATE TABLE IF NOT EXISTS integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  name text NOT NULL, category text NOT NULL, provider_key text NOT NULL, api_version text NOT NULL,
  environment text NOT NULL DEFAULT 'production' CHECK (environment IN ('test','development','staging','production')),
  status text NOT NULL DEFAULT 'not_configured' CHECK (status IN ('configured','not_configured','configuration_required','healthy','degraded','unavailable','authentication_failed','rate_limited','provider_error')),
  enabled boolean NOT NULL DEFAULT false, base_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(clinic_id, provider_key)
);
CREATE TABLE IF NOT EXISTS integration_capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, capability text NOT NULL, supported boolean NOT NULL DEFAULT false, version text, UNIQUE(integration_id, capability));
CREATE TABLE IF NOT EXISTS integration_credentials_metadata (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, credential_ref text NOT NULL, credential_type text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','expired','revoked','rotation_required')), expires_at timestamptz, rotated_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(integration_id, credential_ref));
CREATE TABLE IF NOT EXISTS integration_health (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, state text NOT NULL, latency_ms numeric, error_code text, checked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS external_references (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, provider_object_type text NOT NULL, external_id text NOT NULL, internal_id text NOT NULL, source text NOT NULL, sync_status text NOT NULL DEFAULT 'current', first_seen_at timestamptz NOT NULL DEFAULT now(), last_synchronized_at timestamptz, UNIQUE(integration_id, provider_object_type, external_id), UNIQUE(integration_id, provider_object_type, internal_id));
CREATE TABLE IF NOT EXISTS integration_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, operation text NOT NULL, idempotency_key text, correlation_id text, request_id text, status text NOT NULL, provider_status integer, external_reference text, latency_ms numeric, error_code text, retry_count integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE(clinic_id, integration_id, idempotency_key));
CREATE TABLE IF NOT EXISTS webhook_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, event_id text NOT NULL, event_type text NOT NULL, status text NOT NULL CHECK (status IN ('received','authenticated','deduplicated','validated','normalized','persisted','processed','acknowledged','validation_failed','processing_failed','dead_letter')), correlation_id text, received_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, retry_count integer NOT NULL DEFAULT 0, error_code text, UNIQUE(integration_id, event_id));
CREATE TABLE IF NOT EXISTS synchronization_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, mode text NOT NULL CHECK (mode IN ('initial_sync','incremental_sync','manual_sync','webhook_sync','reconciliation')), status text NOT NULL, cursor_value text, records_processed integer NOT NULL DEFAULT 0, records_failed integer NOT NULL DEFAULT 0, error_code text, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE IF NOT EXISTS integration_failures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, event_id uuid REFERENCES integration_requests(id) ON DELETE SET NULL, error_class text NOT NULL, error_message text NOT NULL, retry_count integer NOT NULL DEFAULT 0, next_retry_at timestamptz, resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS provider_rate_limits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE, integration_id uuid NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, window_key text NOT NULL, request_count integer NOT NULL DEFAULT 0, limit_value integer, remaining_value integer, retry_after timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(integration_id, window_key));

CREATE INDEX IF NOT EXISTS idx_integrations_clinic ON integrations(clinic_id,status);
CREATE INDEX IF NOT EXISTS idx_integration_capabilities_clinic ON integration_capabilities(clinic_id,integration_id);
CREATE INDEX IF NOT EXISTS idx_credentials_clinic ON integration_credentials_metadata(clinic_id,integration_id);
CREATE INDEX IF NOT EXISTS idx_health_clinic ON integration_health(clinic_id,integration_id,checked_at);
CREATE INDEX IF NOT EXISTS idx_external_refs_clinic ON external_references(clinic_id,provider_object_type,internal_id);
CREATE INDEX IF NOT EXISTS idx_integration_requests_clinic ON integration_requests(clinic_id,created_at);
CREATE INDEX IF NOT EXISTS idx_webhook_events_clinic ON webhook_events(clinic_id,received_at);
CREATE INDEX IF NOT EXISTS idx_sync_runs_clinic ON synchronization_runs(clinic_id,started_at);
CREATE INDEX IF NOT EXISTS idx_integration_failures_clinic ON integration_failures(clinic_id,created_at);
CREATE INDEX IF NOT EXISTS idx_rate_limits_clinic ON provider_rate_limits(clinic_id,integration_id);

DO $$ DECLARE t text; BEGIN FOR t IN SELECT unnest(ARRAY['integrations','integration_capabilities','integration_credentials_metadata','integration_health','external_references','integration_requests','webhook_events','synchronization_runs','integration_failures','provider_rate_limits']) LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
 EXECUTE format('DROP POLICY IF EXISTS phase7_tenant_select ON %I',t); EXECUTE format('DROP POLICY IF EXISTS phase7_tenant_write ON %I',t);
 EXECUTE format('CREATE POLICY phase7_tenant_select ON %I FOR SELECT TO authenticated USING (clinic_id IN (SELECT id FROM clinics WHERE clerk_org_id=current_setting(''app.clerk_org_id'',true)))',t);
 EXECUTE format('CREATE POLICY phase7_tenant_write ON %I FOR ALL TO authenticated USING (clinic_id IN (SELECT id FROM clinics WHERE clerk_org_id=current_setting(''app.clerk_org_id'',true))) WITH CHECK (clinic_id IN (SELECT id FROM clinics WHERE clerk_org_id=current_setting(''app.clerk_org_id'',true)))',t);
 EXECUTE format('REVOKE ALL ON %I FROM anon',t); EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO authenticated',t);
 END LOOP; END $$;
