"use client";
import Link from 'next/link';
import {useAgents,useOperationsSummary} from '@/hooks/useAgents';
import {AGENT_DESCRIPTIONS,AGENT_LABELS,type AgentReadiness,type AgentType} from '@/types/agent';
import {AgentStatus} from '@/components/ui/ai';
import {Button,Card,EmptyState,ErrorState,Skeleton} from '@/components/ui/primitives';
import {ContentContainer,PageHeader,PageSection} from '@/components/ui/layout';
function readinessFromApi(value:string):AgentReadiness{return value==='ready'||value==='available'?'ready':value==='disabled'?'disabled':value==='not_configured'?'not_configured':'unavailable'}
export default function DashboardPage(){const agents=useAgents();const ops=useOperationsSummary();const loading=agents.loading||ops.loading;const error=agents.error||ops.error;const reload=()=>{void agents.reload();void ops.reload()};return <main className='hz-page'><ContentContainer><PageSection><PageHeader eyebrow='Operations command center' title='Command Center' description='Authoritative organization-scoped operational state.' actions={<Button variant='secondary' onClick={reload}>Refresh</Button>}/>
<div className='mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>{[['Patients',ops.summary?.patients],['Appointments today',ops.summary?.appointments_today],['Open tasks',ops.summary?.open_tasks],['Escalated tasks',ops.summary?.escalated_tasks],['Active executions',ops.summary?.active_executions],['Completed executions (24h)',ops.summary?.completed_executions_24h]].map(([label,value])=><Card key={String(label)} className='p-5'><p className='hz-label'>{label}</p><h2 className='mt-3 text-2xl font-semibold'>{value===undefined?'—':value}</h2></Card>)}</div>
<div className='mt-6'><div className='mb-4 flex items-end justify-between gap-4'><div><h2 className='text-lg font-semibold'>AI workforce readiness</h2><p className='mt-1 text-sm text-slate-600'>Readiness is configuration/availability, not live execution.</p></div><Link href='/dashboard/agents' className='text-sm font-semibold text-slate-700 hover:text-slate-950'>Open workforce →</Link></div>{error?<ErrorState description={error} onRetry={reload}/>:loading?<div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-5'>{Array.from({length:10},(_,i)=><Skeleton key={i} className='h-32'/>)}</div>:agents.agents.length===0?<EmptyState title='No workforce data available' description='The organization-scoped workforce service did not return any agent records.'/>:<div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-5'>{agents.agents.map(agent=>{const id=agent.id as AgentType;return <Card key={agent.id} className='p-4'><div className='flex items-start justify-between gap-3'><div><h3 className='text-sm font-semibold'>{AGENT_LABELS[id]??agent.name}</h3><p className='mt-2 text-xs leading-5 text-slate-600'>{agent.description??AGENT_DESCRIPTIONS[id]??'Organization-scoped healthcare operations agent.'}</p></div><AgentStatus state={readinessFromApi(agent.status)}/></div></Card>})}</div>}</div></PageSection></ContentContainer></main>}
