"use client";
import Link from "next/link";
import { useAgents } from "@/hooks/useAgents";
import { AGENT_DESCRIPTIONS, AGENT_LABELS, type AgentReadiness, type AgentType } from "@/types/agent";
import { AgentStatus } from "@/components/ui/ai";
import { Button, Card, EmptyState, ErrorState, Skeleton } from "@/components/ui/primitives";
import { ContentContainer, PageHeader, PageSection } from "@/components/ui/layout";

function readinessFromApi(value: string): AgentReadiness { if (value === "ready" || value === "available") return "ready"; if (value === "disabled") return "disabled"; if (value === "not_configured") return "not_configured"; return "unavailable"; }

export default function DashboardPage() {
  const { agents, loading, error, reload } = useAgents();
  return <main className="hz-page"><ContentContainer><PageSection><PageHeader eyebrow="Operations command center" title="Command Center" description="A truthful view of organization-scoped work and workforce readiness. Runtime activity appears only when supplied by the backend." actions={<Button variant="secondary" onClick={() => reload()}>Refresh</Button>} />
    <div className="mt-6 grid gap-4 lg:grid-cols-3"><Card className="p-5"><p className="hz-label">Needs attention</p><h2 className="mt-3 text-lg font-semibold">No live queue</h2><p className="mt-2 text-sm leading-6 text-slate-600">Attention items will appear when organization-scoped workflow data is available.</p></Card><Card className="p-5"><p className="hz-label">Human approvals</p><h2 className="mt-3 text-lg font-semibold">No approval data</h2><p className="mt-2 text-sm leading-6 text-slate-600">Consequential or uncertain work will be surfaced here when the execution service provides it.</p></Card><Card className="p-5"><p className="hz-label">Activity</p><h2 className="mt-3 text-lg font-semibold">No live activity</h2><p className="mt-2 text-sm leading-6 text-slate-600">HEZQARA does not manufacture events, savings, alerts, or task counts to fill the workspace.</p></Card></div>
    <div className="mt-6"><div className="mb-4 flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">AI workforce readiness</h2><p className="mt-1 text-sm text-slate-600">Readiness is configuration/availability, not live execution.</p></div><Link href="/dashboard/agents" className="text-sm font-semibold text-slate-700 hover:text-slate-950">Open workforce →</Link></div>{error ? <ErrorState description={error} onRetry={reload} /> : loading ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Array.from({length: 10}, (_, i) => <Skeleton key={i} className="h-32" />)}</div> : agents.length === 0 ? <EmptyState title="No workforce data available" description="The organization-scoped workforce service did not return any agent records." /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{agents.map(agent => { const id = agent.id as AgentType; const readiness = readinessFromApi(agent.status); return <Card key={agent.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{AGENT_LABELS[id] ?? agent.name}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{agent.description ?? AGENT_DESCRIPTIONS[id] ?? "Organization-scoped healthcare operations agent."}</p></div><AgentStatus state={readiness} /></div></Card>; })}</div>}</div>
  </PageSection></ContentContainer></main>;
}
