"use client";
import Link from "next/link";
import { useAgents } from "@/hooks/useAgents";
import { AGENT_DESCRIPTIONS, AGENT_LABELS, type AgentType, type AgentStatus, agentStatusColor } from "@/types/agent";

function normalizeStatus(value:string):AgentStatus{const allowed:AgentStatus[]=["active","idle","processing","error","disabled","busy"];return allowed.includes(value as AgentStatus)?value as AgentStatus:"idle";}

export default function DashboardPage(){
 const {agents,loading,error}=useAgents();
 return <section className="space-y-8 p-5 sm:p-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Operations command center</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Good to see you.</h1><p className="mt-2 text-sm leading-6 text-slate-500">A truthful view of the work HEZQARA can currently see and the workforce available to your organization.</p></div><Link href="/dashboard/agents" className="inline-flex w-fit rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800">View workforce</Link></header>
 {error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:null}
 <div className="grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Needs attention</p><h2 className="mt-3 text-lg font-bold">No live workflow queue</h2><p className="mt-2 text-sm leading-6 text-slate-500">Attention items will appear here when organization-scoped workflow data is available.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Human approvals</p><h2 className="mt-3 text-lg font-bold">Nothing waiting</h2><p className="mt-2 text-sm leading-6 text-slate-500">HEZQARA will surface consequential or uncertain work that requires a person.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Activity</p><h2 className="mt-3 text-lg font-bold">No live activity yet</h2><p className="mt-2 text-sm leading-6 text-slate-500">We do not manufacture operational activity to make this dashboard look busy.</p></article></div>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-950">AI workforce readiness</h2><p className="mt-1 text-sm text-slate-500">Organization-scoped workforce inventory. Readiness is not the same as live execution.</p></div><Link href="/dashboard/agents" className="text-sm font-semibold text-slate-700 hover:text-slate-950">Open workforce →</Link></div>{loading?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Array.from({length:10},(_,i)=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:agents.length===0?<div className="mt-5 rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No agents are available for this organization.</div>:<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{agents.map(agent=>{const status=normalizeStatus(agent.status);return <div key={agent.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:agentStatusColor(status)}} aria-hidden="true"/><span className="text-sm font-bold text-slate-950">{AGENT_LABELS[agent.id as AgentType]??agent.name}</span></div><p className="mt-2 text-xs capitalize text-slate-500">{status}</p><p className="mt-2 text-xs leading-5 text-slate-500">{AGENT_DESCRIPTIONS[agent.id as AgentType]??"Organization-scoped healthcare operations agent."}</p></div>})}</div>}</section>
 </section>;
}
